In [80]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
import sys
import PIL
from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import load_img

DIRDATA = "./todaslascaras/original"
SOLOCARAS = "./todaslascaras/SOLOCARAS"
TODASLASCARAS = "./todaslascaras"
PREPRO = "./todaslascaras/prepro-2.0"
#CATEGORIES = ["anger", "disgust"]
CATEGORIES = ["anger", "fear", "happy", "joy", "kiss", "neutral", "sadness", "surprise"]
ANGER = ["anger"]
OBJECTIVEDATA = "./todaslascaras/prepro-2.0"



PRIMERO OBTENGO EL RECUADRO DE LA CARA Y LO GUARDO EN UN DIRECTORIO, SEPARANDO POR CLASES

In [71]:
def detectar_y_guardar_cara(path, savePath, category):
    count = 0
    for img in os.listdir(path):
        count += 1
        image = cv2.imread(path+'/'+img)
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        faceCascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")
        faces = faceCascade.detectMultiScale(
            gray,
            scaleFactor=1.03,
            minNeighbors=6,
            minSize=(30, 30)
        )
        for (x, y, w, h) in faces:
            cv2.rectangle(image, (x, y), (x + w, y + h), (0, 255, 0), 2)
            roi_color = image[y:y + h, x:x + w]
            cv2.imwrite(savePath + '/' + category +  str(w) + str(h) + '_faces.jpg', roi_color)


In [47]:
def generar_imagenes(where, categories):
    for category in categories:
        path = os.path.join(DIRDATA, category)
        detectar_y_guardar_cara(path, where+'/'+category, category)

In [73]:
generar_imagenes(where='todaslascaras/SOLOCARAS', categories=CATEGORIES)

./todaslascaras/original/anger
todaslascaras/SOLOCARAS/anger
COUNT: %s -- s037-04_img.tif 1
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
COUNT: %s -- s023-04_img.tif 2
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
COUNT: %s -- s024-04_img.tif 15
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [ 

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [190 190 190]
  ...
  [ 95  95  95]
  [ 97  97  97]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [230 230 230]
  ...
  [167 167 167]
  [171 171 171]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [225 225 225]
  ...
  [167 167 167]
  [169 169 169]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
COUNT: %s -- s012-04_img.tif 25
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [ 

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [ 64  64  64]
  ...
  [ 50  50  50]
  [ 48  48  48]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [227 227 227]
  ...
  [217 217 217]
  [217 217 217]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [227 227 227]
  ...
  [217 217 217]
  [217 217 217]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
COUNT: %s -- google_366.jpg 39
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [ 58  58  58]
  ...
  [ 33  33  33]
  [ 35  35  35]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
./todaslascaras/original/fear
todaslascaras/SOLOCARAS/fear
COUNT: %s -- s010-06_img.tif 1
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0  24   0]
  [  0  21   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0  27   0]
  [  0  11   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
COUNT: %s -- s021-06_img.tif 15
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [ 

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [ 60  60  60]
  ...
  [ 96  96  96]
  [ 88  88  88]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [ 56  56  56]
  ...
  [105 105 105]
  [104 104 104]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [ 56  56  56]
  ...
  [104 104 104]
  [103 103 103]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
COUNT: %s -- google_132.jpg 27
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [207 207 207]
  ...
  [ 32  32  32]
  [ 32  32  32]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [ 58  78  91]
  ...
  [ 24  51  52]
  [ 46  60  57]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [ 56  78  91]
  ...
  [ 27  41  57]
  [ 56  62  70]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
./todaslascaras/original/happy
todaslascaras/SOLOCARAS/happy
COUNT: %s -- google_035.jpg 1
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [ 22  22  22]
  ...
  [ 62  62  62]
 

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [243 243 243]
  ...
  [231 231 231]
  [234 234 234]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [253 253 253]
  ...
  [124 124 124]
  [121 121 121]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [253 253 253]
  ...
  [125 125 125]
  [122 122 122]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
COUNT: %s -- google_013.jpg 13
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [ 12  12  12]
  ...
  [  9   9   9]
  [ 10  10  10]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [168 168 168]
  ...
  [254 254 254]
  [254 254 254]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [148 148 148]
  ...
  [254 254 254]
  [254 254 254]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [148 148 148]
  ...
  [254 254 254]
  [254 254 254]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
COUNT: %s -- google_085.jpg 27
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [142 142 142]
  ...
  [ 42  42  42]
  [ 42  42  42]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [ 32  32  32]
  ...
  [ 43  43  43]
  [ 42  42  42]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [ 86  86  86]
  ...
  [ 37  37  37]
  [ 39  39  39]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [ 84  84  84]
  ...
  [ 38  38  38]
  [ 39  39  39]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
COUNT: %s -- google_193.jpg 39
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [146 146 146]
  ...
  [209 209 209]
  [209 209 209]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [  0   7   0]
  ...
  [  0  24   0]
  [  0  27   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0  11   0]
  ...
  [  0  24   0]
  [  0  30   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [144 150 210]
  ...
  [113 140 183]
  [111 135 182]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [121 147 191]
  ..

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [  0   7   0]
  ...
  [  0  14   0]
  [  0  18   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   7   0]
  ...
  [  0  14   0]
  [  0  11   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
COUNT: %s -- s033-01_img.tif 27
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [ 

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [ 73 103 159]
  ...
  [ 71  86 128]
  [ 58  78 120]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [100 131 174]
  ..

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
COUNT: %s -- s029-09_img.tif 23
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [ 

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  5   5   5]
  ...
  [106 106 106]
  [115 115 115]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [154 154 154]
  ...
  [134 134 134]
  [134 134 134]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [154 154 154]
  ...
  [134 134 134]
  [134 134 134]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
COUNT: %s -- google_182.jpg 7
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [169 169 169]
  ...
  [ 79  79  79]
  [ 84  84  84]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [ 80  80  80]
  ...
  [152 152 152]
  [137 137 137]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [ 65  65  65]
  ...
  [106 106 106]
  [105 105 105]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [ 56  56  56]
  ...
  [ 89  89  89]
  [ 89  89  89]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
COUNT: %s -- s032-00_img.tif 19
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [ 

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [106 106 106]
  ...
  [ 55  55  55]
  [ 48  48  48]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [215 215 215]
  ...
  [225 225 225]
  [225 225 225]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [216 216 216]
  ...
  [225 225 225]
  [225 225 225]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
COUNT: %s -- s021-00_img.tif 32
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [ 

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [  0  18   0]
  ...
  [  0  18   0]
  [  0  24   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0  14   0]
  ...
  [  7  21   0]
  [  0  14   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [111 134 177]
  ...
  [157 166 222]
  [152 166 219]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [134 158 195]
  ..

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [167 167 167]
  ...
  [178 178 178]
  [180 180 180]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [ 17  17  17]
  ...
  [ 28  28  28]
  [ 28  28  28]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [ 15  15  15]
  ...
  [ 27  27  27]
  [ 27  27  27]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
COUNT: %s -- google_022.jpg 11
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [ 80  80  80]
  ...
  [197 197 197]
  [198 198 198]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [165 165 165]
  ...
  [118 118 118]
  [118 118 118]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [204 204 204]
  ...
  [164 164 164]
  [159 159 159]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [200 200 200]
  ...
  [162 162 162]
  [157 157 157]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
COUNT: %s -- google_027.jpg 25
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [ 66  66  66]
  ...
  [ 92  92  92]
  [ 96  96  96]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [ 59  59  59]
  ...
  [121 121 121]
  [141 141 141]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [ 19  19  19]
  ...
  [ 24  24  24]
  [ 24  24  24]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [ 21  21  21]
  ...
  [ 23  23  23]
  [ 23  23  23]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
COUNT: %s -- google_251.jpg 39
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [195 195 195]
  ...
  [229 229 229]
  [230 230 230]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [252 252 252]
  ...
  [255 255 255]
  [255 255 255]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [ 25  25  25]
  ...
  [210 210 210]
  [212 212 212]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [ 26  26  26]
  ...
  [209 209 209]
  [211 211 211]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
COUNT: %s -- google_147.jpg 3
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [106 106 106]
  ...
  [ 53  53  53]
  [ 55  55  55]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [255 255 255]
  ...
  [ 60  60  60]
  [ 60  60  60]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [ 76  76  76]
  ...
  [199 199 199]
  [201 201 201]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [ 75  75  75]
  ...
  [199 199 199]
  [201 201 201]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
COUNT: %s -- google_109.jpg 17
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  9   9   9]
  ...
  [ 21  21  21]
  [ 20  20  20]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  

A CONTINUACION SE ESPEJAN TODAS LAS CARAS Y SE GUARDAN EN EL DIRECTORIO 'SOLOCARAS'

In [74]:
#Con esto leo la imagen y la devuelvo en el color que me indican
def leer_imagen(img_path, gray_scale=False):
    image_src = cv2.imread(img_path)
    if gray_scale:
        image_rgb = cv2.cvtColor(image_src, cv2.COLOR_BGR2GRAY)
    else:
        image_rgb = cv2.cvtColor(image_src, cv2.COLOR_BGR2RGB)
    return image_rgb

#Este metodo espeja una imagen que viene por parametro y la devuelve
def espejar_imagen(img_path, gris=False):
    img = leer_imagen(img_path, gris)
    img_mirrored = np.fliplr(img)
    return img_mirrored


In [77]:
def guardar_imagen(img, name, where):
    cv2.imwrite(where + '/' + name, img)

def espejar_todo(where, categories):
    for category in categories:
        path = os.path.join(SOLOCARAS, category)
        for img in os.listdir(path):
            mirrored_img = espejar_imagen(path+'/'+img, gris = True)
            guardar_imagen(mirrored_img, img + '_mirrored.jpg', where = where +'/'+category)


In [79]:
espejar_todo(where=SOLOCARAS,categories=CATEGORIES)

CON LAS CARAS ESPEJADAS, TOMO CADA IMAGEN Y OBTENGO 10 COPIAS ROTADAS EN UN GRADO DE 22

In [81]:
rotate_gen = ImageDataGenerator(rotation_range=22)
def rotar_y_guardar(cantidadImagenes, path, category):
    for img in os.listdir(path):
            i = load_img(path+'/'+img, color_mode="grayscale", target_size=(120,120))
            i = img_to_array(i)
            i = np.expand_dims(i, axis=0)
            PREFIX = category
            imGen = rotate_gen.flow(i, batch_size=1, save_to_dir=PREPRO+'/'+category, save_prefix=PREFIX, save_format='jpg')
            for x in range(cantidadImagenes):
                batch = imGen.next()

In [83]:
def rotar_caras():
    for category in CATEGORIES:
        path = os.path.join(SOLOCARAS, category)
        rotar_y_guardar(10, SOLOCARAS+'/'+category, category)

In [84]:
rotar_caras()